stages:
  - lint
  - test

# Проверка синтаксиса Java-кода с Checkstyle
java_lint:
  stage: lint
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - echo "Проверка синтаксиса Java с Checkstyle..."
    - mvn clean checkstyle:check
  artifacts:
    when: always
    paths:
      - target/checkstyle-result.xml
    expire_in: 1 week
  tags:
    - docker
  only:
    - dev

# Запускаем только при пуше в ветку main
maven_test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - echo "Running tests..."
    - mvn clean test -Dtest=!ru.korevg.bookreactapp.it.BookItTest
  only:
    - dev
  tags:
    - maven
