version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Порт для AMQP
      - "15672:15672"  # Порт для веб-интерфейса
    environment:
      RABBITMQ_DEFAULT_USER: book         # Имя пользователя по умолчанию
      RABBITMQ_DEFAULT_PASS: password     # Пароль по умолчанию
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq   # Хранение данных RabbitMQ

  books_db:
    image: postgres
    container_name: books_db
    environment:
      POSTGRES_USER: b2b
      POSTGRES_PASSWORD: b2b
      POSTGRES_DB: books
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
  rabbitmq_data:
