cloud:
  dbase-host: localhost:5432
  rabbitmq-host: localhost
  elastic-host: localhost

spring:
  elasticsearch:
    uris: http://${cloud.elastic-host}:9200
    username: elastic
    password: password
    repositories:
      enabled: false

  application:
    name: BookReactApp
  r2dbc:
    url: r2dbc:postgresql://${cloud.dbase-host}/books
    username: b2b
    password: b2b
    pool:
      max-size: 20
      initial-size: 5
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://${cloud.dbase-host}/books
    user: b2b
    password: b2b
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  codec:
    max-in-memory-size: 20MB
  rabbitmq:
    host: ${cloud.rabbitmq-host}
    port: 5672
    username: book
    password: password
  topic-exchange:
    name: producer
  books:
    queue:
      name: books
      routing-key: books

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

